// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvfngdrucqptgfjqxpyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2Zm5nZHJ1Y3FwdGdmanF4cHlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMzY3MjQsImV4cCI6MjA1ODkxMjcyNH0.EwpD14bb6dDWpjKuxBmqBVg-2ojvzQ5kORwrzteO9dg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
