// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibbukhlelbpgxedoqrni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliYnVraGxlbGJwZ3hlZG9xcm5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjMxMDksImV4cCI6MjA2NDMzOTEwOX0.HL3Myme8lNt6-0GkHSuh81EI6YmFFL-d5Zk3pDMhERE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
