// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";
import { SuspenseWrapper } from "./components/SuspenseWrapper";

const App = lazy(() => import("./pages/App.tsx"));
const Payment = lazy(() => import("./pages/PaymentProtected.tsx"));
const Course = lazy(() => import("./pages/CourseProtected.tsx"));
const PaymentSuccess = lazy(() => import("./pages/PaymentSuccessProtected.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const SignUp = lazy(() => import("./pages/SignUp.tsx"));
const About = lazy(() => import("./pages/About.tsx"));
const Contact = lazy(() => import("./pages/Contact.tsx"));
const Faqs = lazy(() => import("./pages/Faqs.tsx"));
const PrivacyPolicy = lazy(() => import("./pages/PrivacyPolicy.tsx"));
const TermsOfUse = lazy(() => import("./pages/TermsOfUse.tsx"));
const RefundPolicy = lazy(() => import("./pages/RefundPolicy.tsx"));

export const userRoutes: RouteObject[] = [
	{ index: true, element: <SuspenseWrapper><App /></SuspenseWrapper>},
	{ path: "login", element: <SuspenseWrapper><Login /></SuspenseWrapper>},
	{ path: "signup", element: <SuspenseWrapper><SignUp /></SuspenseWrapper>},
	{ path: "about", element: <SuspenseWrapper><About /></SuspenseWrapper>},
	{ path: "contact", element: <SuspenseWrapper><Contact /></SuspenseWrapper>},
	{ path: "faqs", element: <SuspenseWrapper><Faqs /></SuspenseWrapper>},
	{ path: "payment", element: <SuspenseWrapper><Payment /></SuspenseWrapper>},
	{ path: "payment-success", element: <SuspenseWrapper><PaymentSuccess /></SuspenseWrapper>},
	{ path: "course", element: <SuspenseWrapper><Course /></SuspenseWrapper>},
	{ path: "privacy-policy", element: <SuspenseWrapper><PrivacyPolicy /></SuspenseWrapper>},
	{ path: "terms-of-use", element: <SuspenseWrapper><TermsOfUse /></SuspenseWrapper>},
	{ path: "refund-policy", element: <SuspenseWrapper><RefundPolicy /></SuspenseWrapper>},
];
