
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";



const App = lazy(() => import("./pages/App.tsx"));
const Course = lazy(() => import("./pages/Course.tsx"));
const Payment = lazy(() => import("./pages/Payment.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/course", element: <Course />},
	{ path: "/payment", element: <Payment />},

];
